# Generated by Django 4.0.5 on 2022-06-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_vpn_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vpnconnection',
            options={'ordering': ('remote_organisation',)},
        ),
        migrations.RenameField(
            model_name='vpnconnection',
            old_name='gegenstelle',
            new_name='remote_organisation',
        ),
    ]
