# Generated by Django 4.0.5 on 2022-06-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_vpn_plugin', '0002_alter_vpnconnection_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpnconnection',
            old_name='remote_ip',
            new_name='remote_gateway_ip',
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='accept_peer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='accept_types',
            field=models.CharField(default='any peer id', max_length=50),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='auth_method',
            field=models.CharField(default='pre-shared key', max_length=50),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='authentication',
            field=models.CharField(default='AES256', max_length=50),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='change_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='dead_pear_detection',
            field=models.CharField(default='disable', max_length=50),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='dh_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='encrytion',
            field=models.CharField(default='AES256', max_length=50),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='ike_version',
            field=models.CharField(default='V2', max_length=50),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='key_lifetime',
            field=models.CharField(default='3600', max_length=100),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='local_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='nat_traversal',
            field=models.CharField(default='disable', max_length=50),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='pre_shared_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='status',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='vpnconnection',
            name='ordered_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
