# Generated by Django 4.0.5 on 2022-06-23 13:35

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0073_journalentry_tags_custom_fields'),
        ('netbox_vpn_plugin', '0003_rename_remote_ip_vpnconnection_remote_gateway_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnConnectionPhase2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=50)),
                ('local_address', models.GenericIPAddressField(blank=True, null=True)),
                ('remote_address', models.GenericIPAddressField(blank=True, null=True)),
                ('encrytion', models.CharField(default='AES256', max_length=50)),
                ('authentication', models.CharField(default='AES256', max_length=50)),
                ('dh_group', models.CharField(blank=True, max_length=50, null=True)),
                ('key_lifetime', models.CharField(default='3600', max_length=100)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('vpn_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='netbox_vpn_plugin.vpnconnection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
