# Generated by Django 4.0.5 on 2022-06-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0153_created_datetimefield'),
        ('extras', '0073_journalentry_tags_custom_fields'),
        ('tenancy', '0007_contact_link'),
        ('netbox_vpn_plugin', '0003_alter_vpn_tenant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vpn',
            new_name='VpnList',
        ),
    ]
