# Generated by Django 4.0.5 on 2022-06-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_vpn_plugin', '0004_vpnconnectionphase2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vpnconnectionphase2',
            options={'ordering': ('vpn_connection', 'name')},
        ),
    ]
