# Generated by Django 4.0.5 on 2022-06-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0073_journalentry_tags_custom_fields'),
        ('tenancy', '0007_contact_link'),
        ('dcim', '0153_created_datetimefield'),
        ('netbox_vpn_plugin', '0004_rename_vpn_vpnlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VpnList',
            new_name='VpnConnection',
        ),
    ]
