# Generated by Django 4.0.5 on 2022-06-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_vpn_plugin', '0005_alter_vpnconnectionphase2_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnconnectionphase2',
            name='vpn_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase2', to='netbox_vpn_plugin.vpnconnection'),
        ),
    ]
