# Generated by Django 4.0.5 on 2022-06-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_vpn_plugin', '0006_rename_orginator_vpnconnection_vpn_endpoint_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpnconnection',
            old_name='vpn_endpoint',
            new_name='orginator',
        ),
        migrations.RemoveField(
            model_name='vpnconnection',
            name='active_since',
        ),
        migrations.RemoveField(
            model_name='vpnconnection',
            name='ordered_by',
        ),
    ]
