# Generated by Django 4.0.5 on 2022-06-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_vpn_plugin', '0007_rename_vpn_endpoint_vpnconnection_orginator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpnconnection',
            old_name='orginator',
            new_name='vpn_endpoint',
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='active_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='ordered_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
