# Generated by Django 4.0.5 on 2022-06-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0153_created_datetimefield'),
        ('netbox_vpn_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpn',
            name='orginator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='dcim.device'),
        ),
        migrations.AddField(
            model_name='vpn',
            name='remote_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
