# Generated by Django 4.0.5 on 2022-06-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_vpn_plugin', '0005_rename_vpnlist_vpnconnection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpnconnection',
            old_name='orginator',
            new_name='vpn_endpoint',
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='active_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vpnconnection',
            name='ordered_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
